/* CARNET PRO WORLD8 public façade — production */
window.DIGIY_WORLD8_PAGE={
  "en": {
    "Activité · preuves · 0% commission": "Activity · evidence · 0% commission",
    "Fonctions": "Features",
    "Doctrine CARNET": "CARNET doctrine",
    "Note vocale": "Voice note",
    "📝 Demande CARNET PRO": "📝 CARNET PRO request",
    "💳 Tarifs": "💳 Pricing",
    "🔐 Ouvrir PRO CARNET": "🔐 Open PRO CARNET",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "Your activity.",
    "Claire.": "Clear.",
    "Sans brouillard.": "No fog.",
    "0% commission": "0% commission",
    "Argent direct au pro": "Money goes directly to the pro",
    "PRO + PERSO": "PRO + PERSONAL",
    "Bilan auto": "Automatic summary",
    "Alerte trésorerie": "Cash-flow alert",
    "Sauvegarde JSON": "JSON backup",
    "Situation PRO — aujourd’hui": "PRO situation — today",
    "Vue immédiate · mise à jour à chaque trace": "Immediate view · updated with every entry",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ Balance updated with every entry",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "No-commitment CARNET PRO request · Paid activation · 0% commission",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "CARNET PRO helps the professional understand the business. DIGIY never touches the cashbox.",
    "✅ Demande initiale sans engagement": "✅ Initial request with no commitment",
    "📒 Activation CARNET PRO payante": "📒 Paid CARNET PRO activation",
    "🤝 Argent et recettes directs au pro": "🤝 Money and revenue go directly to the pro",
    "📊 Situation d’activité plus lisible": "📊 Clearer business activity"
  },
  "es": {
    "Activité · preuves · 0% commission": "Actividad · pruebas · 0% comisión",
    "Fonctions": "Funciones",
    "Doctrine CARNET": "Doctrina CARNET",
    "Note vocale": "Nota de voz",
    "📝 Demande CARNET PRO": "📝 Solicitud CARNET PRO",
    "💳 Tarifs": "💳 Tarifas",
    "🔐 Ouvrir PRO CARNET": "🔐 Abrir PRO CARNET",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "Tu actividad.",
    "Claire.": "Clara.",
    "Sans brouillard.": "Sin niebla.",
    "0% commission": "0% comisión",
    "Argent direct au pro": "Dinero directo al profesional",
    "PRO + PERSO": "PRO + PERSONAL",
    "Bilan auto": "Balance automático",
    "Alerte trésorerie": "Alerta de tesorería",
    "Sauvegarde JSON": "Copia JSON",
    "Situation PRO — aujourd’hui": "Situación PRO — hoy",
    "Vue immédiate · mise à jour à chaque trace": "Vista inmediata · actualizada en cada registro",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ Saldo actualizado con cada registro",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "Solicitud CARNET PRO sin compromiso · Activación de pago · 0% comisión",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "CARNET PRO ayuda al profesional a leer su actividad. DIGIY no toca su caja.",
    "✅ Demande initiale sans engagement": "✅ Solicitud inicial sin compromiso",
    "📒 Activation CARNET PRO payante": "📒 Activación CARNET PRO de pago",
    "🤝 Argent et recettes directs au pro": "🤝 Dinero e ingresos directos al profesional",
    "📊 Situation d’activité plus lisible": "📊 Situación de actividad más clara"
  },
  "pt": {
    "Activité · preuves · 0% commission": "Atividade · comprovativos · 0% de comissão",
    "Fonctions": "Funções",
    "Doctrine CARNET": "Doutrina CARNET",
    "Note vocale": "Nota de voz",
    "📝 Demande CARNET PRO": "📝 Pedido CARNET PRO",
    "💳 Tarifs": "💳 Preços",
    "🔐 Ouvrir PRO CARNET": "🔐 Abrir PRO CARNET",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "A tua atividade.",
    "Claire.": "Clara.",
    "Sans brouillard.": "Sem nevoeiro.",
    "0% commission": "0% de comissão",
    "Argent direct au pro": "Dinheiro direto ao profissional",
    "PRO + PERSO": "PRO + PESSOAL",
    "Bilan auto": "Balanço automático",
    "Alerte trésorerie": "Alerta de tesouraria",
    "Sauvegarde JSON": "Cópia JSON",
    "Situation PRO — aujourd’hui": "Situação PRO — hoje",
    "Vue immédiate · mise à jour à chaque trace": "Visão imediata · atualizada a cada registo",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ Saldo atualizado a cada registo",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "Pedido CARNET PRO sem compromisso · Ativação paga · 0% de comissão",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "CARNET PRO ajuda o profissional a compreender a atividade. A DIGIY não toca na caixa.",
    "✅ Demande initiale sans engagement": "✅ Pedido inicial sem compromisso",
    "📒 Activation CARNET PRO payante": "📒 Ativação CARNET PRO paga",
    "🤝 Argent et recettes directs au pro": "🤝 Dinheiro e receitas diretos ao profissional",
    "📊 Situation d’activité plus lisible": "📊 Situação da atividade mais clara"
  },
  "de": {
    "Activité · preuves · 0% commission": "Aktivität · Nachweise · 0% Provision",
    "Fonctions": "Funktionen",
    "Doctrine CARNET": "CARNET-Doktrin",
    "Note vocale": "Sprachnotiz",
    "📝 Demande CARNET PRO": "📝 CARNET PRO Anfrage",
    "💳 Tarifs": "💳 Preise",
    "🔐 Ouvrir PRO CARNET": "🔐 PRO CARNET öffnen",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "Deine Aktivität.",
    "Claire.": "Klar.",
    "Sans brouillard.": "Ohne Nebel.",
    "0% commission": "0% Provision",
    "Argent direct au pro": "Geld direkt an den Profi",
    "PRO + PERSO": "PRO + PRIVAT",
    "Bilan auto": "Automatische Bilanz",
    "Alerte trésorerie": "Liquiditätswarnung",
    "Sauvegarde JSON": "JSON-Sicherung",
    "Situation PRO — aujourd’hui": "PRO-Situation — heute",
    "Vue immédiate · mise à jour à chaque trace": "Sofortansicht · bei jedem Eintrag aktualisiert",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ Saldo bei jedem Eintrag aktualisiert",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "Unverbindliche CARNET-PRO-Anfrage · Kostenpflichtige Aktivierung · 0% Provision",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "CARNET PRO hilft dem Profi, seine Aktivität zu verstehen. DIGIY berührt die Kasse nicht.",
    "✅ Demande initiale sans engagement": "✅ Unverbindliche Erstanfrage",
    "📒 Activation CARNET PRO payante": "📒 Kostenpflichtige CARNET-PRO-Aktivierung",
    "🤝 Argent et recettes directs au pro": "🤝 Geld und Einnahmen direkt an den Profi",
    "📊 Situation d’activité plus lisible": "📊 Klarere Geschäftslage"
  },
  "it": {
    "Activité · preuves · 0% commission": "Attività · prove · 0% commissioni",
    "Fonctions": "Funzioni",
    "Doctrine CARNET": "Dottrina CARNET",
    "Note vocale": "Nota vocale",
    "📝 Demande CARNET PRO": "📝 Richiesta CARNET PRO",
    "💳 Tarifs": "💳 Tariffe",
    "🔐 Ouvrir PRO CARNET": "🔐 Apri PRO CARNET",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "La tua attività.",
    "Claire.": "Chiara.",
    "Sans brouillard.": "Senza nebbia.",
    "0% commission": "0% commissioni",
    "Argent direct au pro": "Denaro diretto al professionista",
    "PRO + PERSO": "PRO + PERSONALE",
    "Bilan auto": "Bilancio automatico",
    "Alerte trésorerie": "Avviso di tesoreria",
    "Sauvegarde JSON": "Backup JSON",
    "Situation PRO — aujourd’hui": "Situazione PRO — oggi",
    "Vue immédiate · mise à jour à chaque trace": "Vista immediata · aggiornata a ogni registrazione",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ Saldo aggiornato a ogni registrazione",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "Richiesta CARNET PRO senza impegno · Attivazione a pagamento · 0% commissioni",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "CARNET PRO aiuta il professionista a leggere la propria attività. DIGIY non tocca la cassa.",
    "✅ Demande initiale sans engagement": "✅ Richiesta iniziale senza impegno",
    "📒 Activation CARNET PRO payante": "📒 Attivazione CARNET PRO a pagamento",
    "🤝 Argent et recettes directs au pro": "🤝 Denaro e ricavi diretti al professionista",
    "📊 Situation d’activité plus lisible": "📊 Situazione dell’attività più chiara"
  },
  "nl": {
    "Activité · preuves · 0% commission": "Activiteit · bewijs · 0% commissie",
    "Fonctions": "Functies",
    "Doctrine CARNET": "CARNET-doctrine",
    "Note vocale": "Spraaknotitie",
    "📝 Demande CARNET PRO": "📝 CARNET PRO aanvraag",
    "💳 Tarifs": "💳 Tarieven",
    "🔐 Ouvrir PRO CARNET": "🔐 PRO CARNET openen",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "Jouw activiteit.",
    "Claire.": "Helder.",
    "Sans brouillard.": "Zonder mist.",
    "0% commission": "0% commissie",
    "Argent direct au pro": "Geld rechtstreeks naar de professional",
    "PRO + PERSO": "PRO + PERSOONLIJK",
    "Bilan auto": "Automatisch overzicht",
    "Alerte trésorerie": "Kaswaarschuwing",
    "Sauvegarde JSON": "JSON-back-up",
    "Situation PRO — aujourd’hui": "PRO-situatie — vandaag",
    "Vue immédiate · mise à jour à chaque trace": "Direct overzicht · bijgewerkt bij elke registratie",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ Saldo bijgewerkt bij elke registratie",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "Vrijblijvende CARNET PRO-aanvraag · Betaalde activering · 0% commissie",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "CARNET PRO helpt de professional de activiteit te begrijpen. DIGIY raakt de kassa niet aan.",
    "✅ Demande initiale sans engagement": "✅ Vrijblijvende eerste aanvraag",
    "📒 Activation CARNET PRO payante": "📒 Betaalde CARNET PRO-activering",
    "🤝 Argent et recettes directs au pro": "🤝 Geld en inkomsten rechtstreeks naar de professional",
    "📊 Situation d’activité plus lisible": "📊 Duidelijker activiteitenoverzicht"
  },
  "ar": {
    "Activité · preuves · 0% commission": "النشاط · الإثباتات · عمولة 0٪",
    "Fonctions": "الوظائف",
    "Doctrine CARNET": "عقيدة CARNET",
    "Note vocale": "ملاحظة صوتية",
    "📝 Demande CARNET PRO": "📝 طلب CARNET PRO",
    "💳 Tarifs": "💳 الأسعار",
    "🔐 Ouvrir PRO CARNET": "🔐 فتح PRO CARNET",
    "📒 DIGIY CARNET PRO by DIGIYLYFE": "📒 DIGIY CARNET PRO by DIGIYLYFE",
    "Ton activité.": "نشاطك.",
    "Claire.": "واضح.",
    "Sans brouillard.": "بدون ضباب.",
    "0% commission": "عمولة 0٪",
    "Argent direct au pro": "المال مباشرة للمهني",
    "PRO + PERSO": "مهني + شخصي",
    "Bilan auto": "حصيلة تلقائية",
    "Alerte trésorerie": "تنبيه السيولة",
    "Sauvegarde JSON": "نسخة JSON",
    "Situation PRO — aujourd’hui": "وضع النشاط المهني — اليوم",
    "Vue immédiate · mise à jour à chaque trace": "رؤية فورية · تحديث مع كل تسجيل",
    "⚡ Solde mis à jour à chaque trace posée": "⚡ الرصيد يتحدث مع كل تسجيل",
    "Demande CARNET PRO sans engagement · Activation payante · 0% commission": "طلب CARNET PRO بلا التزام · تفعيل مدفوع · عمولة 0٪",
    "CARNET PRO aide le professionnel à lire son activité. DIGIY ne touche pas à sa caisse.": "يساعد CARNET PRO المهني على فهم نشاطه. DIGIY لا يمس صندوقه.",
    "✅ Demande initiale sans engagement": "✅ طلب أولي بلا التزام",
    "📒 Activation CARNET PRO payante": "📒 تفعيل CARNET PRO مدفوع",
    "🤝 Argent et recettes directs au pro": "🤝 المال والإيرادات مباشرة للمهني",
    "📊 Situation d’activité plus lisible": "📊 وضع نشاط أوضح"
  }
};